server {
    listen 80;

    # Redirect root to /station
    location / {
        return 302 /portal/;
    }

    # Serve the React app under /portal
    location /portal/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /portal/index.html;
    }

    # Optional health check
    location /health {
        return 200 "OK";
    }
}
